version: '3'
services:
  app:
    image: vmhub.vietmap.io/platform/vietmap.core.promotion.app:1.0.0
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run build-start