import {
  DeploymentUnitOutlined,
  DollarOutlined,
  GiftOutlined,
  HomeOutlined,
  InfoCircleOutlined,
  ProfileOutlined,
  RadarChartOutlined,
  SettingOutlined,
  TagsOutlined,
  UserOutlined,
  FundProjectionScreenOutlined,
} from '@ant-design/icons';
import LoadableComponent from '../Loadable/index';

export const RouterPath = {
  Dashboard: '/dashboard',
  Members: '/members',
  Promotion: '/promotion',
  Deals: '/deals',
  Setting: '/setting',
  ProjectDetail: '/project-detail/:id',
};

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/original-budget',
    name: 'original-budget',
    permission: '',
    title: 'Original Budget',
    icon: DollarOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/OriginalBudget')),
  },
  {
    path: '/saleplan',
    name: 'saleplan',
    permission: '',
    title: 'Sale Plan',
    icon: FundProjectionScreenOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/SalePlan')),
  },
  {
    path: '/home',
    name: 'home',
    permission: '',
    title: 'Home',
    icon: HomeOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/HomePromotion')),
  },
  {
    // path: '/original-detail/:id',
    path: '/original-detail/detail/:id',
    name: 'OriginalBudgetDetail',
    permission: '',
    title: 'Original Budget Detail',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/OriginalBudget/Detail')),
  },

  //For promotion
  {
    path: '/detailpromotion/:id',
    name: 'Detailpromotion',
    permission: '',
    title: 'Detailpromotion',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Promotion/detailpromotion')),
  },
  {
    path: '/deals',
    name: 'deals',
    permission: '',
    title: 'Deals',
    icon: GiftOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Deals')),
  },
  {
    path: '/setting',
    name: 'setting',
    permission: '',
    title: 'Setting',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Setting')),
  },
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: TagsOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/about',
    permission: '',
    title: 'About',
    name: 'about',
    icon: InfoCircleOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/About')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path: '/workflow',
    permission: '',
    title: 'Workflow',
    name: 'workflow',
    icon: DeploymentUnitOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/workflow')),
  },
  {
    path: '/flow/:id',
    permission: '',
    title: 'Flow',
    name: 'flow',
    icon: RadarChartOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Flow')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
];

export const routers = [...userRouter, ...appRouters];
